import { DataTypes, Model } from 'sequelize';
import type { Optional } from 'sequelize';

import db from '../db/conn.js';
import type { IUser } from '../interfaces/User.js';

/**
 * Attributes required for creating a new User.
 * The 'id' is optional as it is auto-generated by the database.
 */
interface UserCreationAttributes extends Optional<IUser, 'id'> {}

/**
 * User model representing system operators in the 'users' table.
 * Handles authentication credentials and administrative privileges.
 */
class User extends Model<IUser, UserCreationAttributes> implements IUser {
  public id!: number;
  public name!: string;
  public email!: string;
  public password!: string;
  public isAdmin!: boolean;
  public isActive!: boolean;
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;
  public readonly deletedAt!: Date;
}

User.init(
  {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true,
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,
      validate: {
        isEmail: true,
      },
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    isAdmin: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
      allowNull: false,
      field: 'is_admin',
    },
    isActive: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
      allowNull: false,
      field: 'is_active',
    },
  },
  {
    sequelize: db,
    modelName: 'User',
    tableName: 'users',
    timestamps: true,
    paranoid: true,
  },
);

export default User;
